# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/kubectl-doweb
    binary: kubectl-doweb
    goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
